name: README to PDF
on:
  push:
    branches:
      - main
jobs:
  convert:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: /
          output_dir: /pdfs
          images_dir: /img
          image_import: /img
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
  publish:
    name: Publish PDF
    runs-on: ubuntu-latest
    needs: convert
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: pdfs
      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.convert.outputs.upload_url }}
          asset_path: pdfs
          asset_name: README.pdf
          asset_content_type: application/pdf
  